### ISSUE TITLE
Search field bar at Guild Page don't work

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#74] opened 2022-06-27 16:48 UTC
**Description**
When user click on Search field bar at Guild Page, then can see cursor next to magnifying glass icon. But when user enter some title, ENS or address, then nothing appears in field. User should be able to submit title, ENS or address and to see results from search.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box
5. Click on magnifying glass icon next to Create Proposal button
6. Enter title, ENS or address of Proposal which you want to search

**Expected behavior**
Title, ENS or address which enter appear in search field bar. User can search it when press 'Enter', and should see search results.

**Actual behavior**
Title, ENS or address which enter don't appear in search field bar and User can't search it

**Screenshots**
<img width="930" alt="Screenshot 2022-06-27 at 18 47 18" src="https://user-images.githubusercontent.com/37701286/175993324-1b2f4158-471b-4d98-9a9e-cf56be5a7828.png">

**Device Information**

- OS: MacOs
- Browser GoogleChrome, Brave
- Device: MacOS Monterey v12.4

**Additional context**
Expect from Search bar to work and can do some input

**Comment by rossneilson** [comment] 2022-06-28 10:13
Duplicate of #24

**Closed by rossneilson** 2022-06-28 10:13 UTC
