### ISSUE TITLE
Unable to create Proposal with 'Global Permission Registry' action

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#188] opened 2022-08-06 21:22 UTC
**Description**
Unable to create Proposal with 'Global Permission Registry' action after populating all fields and adding action.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button
7. Add Option
8. Click on Add Action button
9. Add 'Global Permission Registry' action with all required data
10. Click on 'Create Proposal' button

**Expected behavior**
Should be able to create Proposal with  'Global Permission Registry' action successfully.

**Screenrecord**
https://user-images.githubusercontent.com/37701286/183266412-46fb90a5-78c4-4ea5-b08a-1aabd02a0a83.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Could the problem be in 'Function to be allowed' should there be something more specific?

**Comment by rossneilson** [comment] 2022-08-08 10:04
Duplicate of #145

**Closed by rossneilson** 2022-08-08 10:04 UTC
Labels: bug
