### ISSUE TITLE
'Mint REP' action tooltips are flickering on hover

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#201] opened 2022-08-09 23:56 UTC
**Description**
On 'Mint REP' form, when I hover tooltip icons the text are kinda flickering.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on 'Create Proposal'
7. Click on 'Add action' button
8. Select 'Mint REP'
9. Hover tooltip icons

**Expected behavior**
Tooltip text should appear without flickering on hover.

**Screen record**
https://user-images.githubusercontent.com/37701286/183781475-08128bf4-5ae5-4f8e-8d41-c12c15417cc3.mp4

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment] 2022-08-15 12:49
Duplicate of #189 I think

**Closed by rossneilson** 2022-08-15 12:49 UTC

**Comment by Filipv95** [comment] 2022-08-15 18:04
@rossneilson I've splitted this into to separate issues because it's regarding different actions i.e. '**Mint REP**' and '**Update ENS Content**'. If both can be fixed in one (#189), that's awesome.
